version: "3.8"
services:
  postgres_db:
    image: postgres:15
    container_name: conejo-motors-db
    restart: always
    environment:
      POSTGRES_DB: conejo_motors_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
